// 分布式树形指令执行系统 —— 协议定义（对应《架构方案 v3.21》3.2 / 3.3 / 3.13 / 4.3 / 5.6）
//
// 约定（必须遵守，跨实现一致性的根基）：
//   * 所有枚举的第一个值一律是 *_UNSPECIFIED = 0，且"未设置"与"显式传 0"必须靠 proto3 optional + has_* 区分；
//   * 凡"必须显式设置"的字段（Target.Mode 等）用 optional，has_* == false 即拒绝；
//   * 时间字段一律 google.protobuf.Timestamp（UTC 秒 + 纳秒），绝不用本地时间字符串；
//   * 摘要 / 签名一律对"canonical 编码"（deterministic serialization，字段按序号）取，
//     repeated 字段在取摘要前显式按 NodeID 的 16 字节大端升序排序。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: node.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_Connect_FullMethodName         = "/treecmd.v1.NodeService/Connect"
	NodeService_FetchCommands_FullMethodName   = "/treecmd.v1.NodeService/FetchCommands"
	NodeService_ReportResult_FullMethodName    = "/treecmd.v1.NodeService/ReportResult"
	NodeService_StreamResult_FullMethodName    = "/treecmd.v1.NodeService/StreamResult"
	NodeService_EnrollChallenge_FullMethodName = "/treecmd.v1.NodeService/EnrollChallenge"
	NodeService_Enroll_FullMethodName          = "/treecmd.v1.NodeService/Enroll"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	// 控制面双向流：注册、心跳、租约续期、健康检查、查询（子主动建立）
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UpFrame, DownFrame], error)
	// 拉取工作队列（seq 增量 + 名下待执行/重投 Assignment）：幂等，可无限重试
	FetchCommands(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	// 上报结果：幂等，可重试（小结果内联）
	ReportResult(ctx context.Context, in *Report, opts ...grpc.CallOption) (*ReportResponse, error)
	// 大结果分片上行：双向流（见 3.13）
	StreamResult(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamFrame, UploadAck], error)
	// 运行期入网：取一次性挑战（**不要求客户端证书**，鉴权靠 PoP + 许可）
	EnrollChallenge(ctx context.Context, in *EnrollChallengeReq, opts ...grpc.CallOption) (*EnrollChallengeResp, error)
	// 运行期入网：提交公钥 + PoP + 许可 → 父用自身 CA 私钥签发身份证书与（可选的）CA 证书
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UpFrame, DownFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[0], NodeService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpFrame, DownFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_ConnectClient = grpc.BidiStreamingClient[UpFrame, DownFrame]

func (c *nodeServiceClient) FetchCommands(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, NodeService_FetchCommands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ReportResult(ctx context.Context, in *Report, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, NodeService_ReportResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) StreamResult(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamFrame, UploadAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[1], NodeService_StreamResult_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamFrame, UploadAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamResultClient = grpc.BidiStreamingClient[StreamFrame, UploadAck]

func (c *nodeServiceClient) EnrollChallenge(ctx context.Context, in *EnrollChallengeReq, opts ...grpc.CallOption) (*EnrollChallengeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollChallengeResp)
	err := c.cc.Invoke(ctx, NodeService_EnrollChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, NodeService_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
type NodeServiceServer interface {
	// 控制面双向流：注册、心跳、租约续期、健康检查、查询（子主动建立）
	Connect(grpc.BidiStreamingServer[UpFrame, DownFrame]) error
	// 拉取工作队列（seq 增量 + 名下待执行/重投 Assignment）：幂等，可无限重试
	FetchCommands(context.Context, *FetchRequest) (*FetchResponse, error)
	// 上报结果：幂等，可重试（小结果内联）
	ReportResult(context.Context, *Report) (*ReportResponse, error)
	// 大结果分片上行：双向流（见 3.13）
	StreamResult(grpc.BidiStreamingServer[StreamFrame, UploadAck]) error
	// 运行期入网：取一次性挑战（**不要求客户端证书**，鉴权靠 PoP + 许可）
	EnrollChallenge(context.Context, *EnrollChallengeReq) (*EnrollChallengeResp, error)
	// 运行期入网：提交公钥 + PoP + 许可 → 父用自身 CA 私钥签发身份证书与（可选的）CA 证书
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) Connect(grpc.BidiStreamingServer[UpFrame, DownFrame]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedNodeServiceServer) FetchCommands(context.Context, *FetchRequest) (*FetchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchCommands not implemented")
}
func (UnimplementedNodeServiceServer) ReportResult(context.Context, *Report) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportResult not implemented")
}
func (UnimplementedNodeServiceServer) StreamResult(grpc.BidiStreamingServer[StreamFrame, UploadAck]) error {
	return status.Error(codes.Unimplemented, "method StreamResult not implemented")
}
func (UnimplementedNodeServiceServer) EnrollChallenge(context.Context, *EnrollChallengeReq) (*EnrollChallengeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrollChallenge not implemented")
}
func (UnimplementedNodeServiceServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServiceServer).Connect(&grpc.GenericServerStream[UpFrame, DownFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_ConnectServer = grpc.BidiStreamingServer[UpFrame, DownFrame]

func _NodeService_FetchCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).FetchCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_FetchCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).FetchCommands(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ReportResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Report)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ReportResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ReportResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ReportResult(ctx, req.(*Report))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_StreamResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServiceServer).StreamResult(&grpc.GenericServerStream[StreamFrame, UploadAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamResultServer = grpc.BidiStreamingServer[StreamFrame, UploadAck]

func _NodeService_EnrollChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollChallengeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).EnrollChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_EnrollChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).EnrollChallenge(ctx, req.(*EnrollChallengeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "treecmd.v1.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchCommands",
			Handler:    _NodeService_FetchCommands_Handler,
		},
		{
			MethodName: "ReportResult",
			Handler:    _NodeService_ReportResult_Handler,
		},
		{
			MethodName: "EnrollChallenge",
			Handler:    _NodeService_EnrollChallenge_Handler,
		},
		{
			MethodName: "Enroll",
			Handler:    _NodeService_Enroll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _NodeService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamResult",
			Handler:       _NodeService_StreamResult_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "node.proto",
}
